### ISSUE TITLE
Fix LRQDO JSON-LD example

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#20]
**Describe the bug**
There is an issue with the JSON-LD provided by LRQDO

**Comment by nclavaud** [comment]
Please be more specific?

If this is about [this url](https://api.thefoodassembly.com/dfc/catalog/5100) having an empty array under property `DFC:supplies`, then this is because this producer does not supply any product to LRQDO at the moment. They used to, at the time the feature was implemented. Maybe they have stopped selling on LRQDO recently?

Here is another example of JSON/LD for another producer:
https://api.thefoodassembly.com/dfc/catalog/3781

**Comment by RachL** [comment]
yes sorry @nclavaud I thought you know, this issue was more of a reminder. I think @simonLouvet wrote you a message?

**Comment by simonLouvet** [comment]
ok @nclavaud this just because this producer does not supply any product. Is there a shared producer on the 3 platforms?

**Comment by simonLouvet** [comment]
In the prototype, only the products sold are considered. In the example it would be 4 Units.
